spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  profiles:
    active: mybatis, jdbc

server:
  port: 1234
